window_hourly:
  start_offset_min: 15
  end_at_target: true
  cancel_buffer_seconds: 2
window_close:
  start: "15:50"
  end: "16:00"
  cancel_buffer_seconds: 2
min_ev_usd: 0.05
max_bins_per_series: 2
